[project]
name = "skn23-3rd-2team"
version = "0.1.0"
description = "현장 기술지원 챗봇 (Robot/Welding)"
authors = [
    {name = "JUYEOP024", email = "juyeobsong63@gmail.com"}
]
readme = "README.md"
requires-python = "~3.12"

dependencies = [
    "langchain (==1.2.10)",
    "langchain-core (>=0.3.0)",
    "langchain-openai (==1.1.10)",
    "langchain-community (==0.4.1)",
    "langchain-text-splitters (>=0.3.0)",
    "langgraph (==1.0.9)",
    "fastapi (==0.129.0)",
    "uvicorn (==0.41.0)",
    "pydantic (==2.12.5)",
    "pydantic-settings (==2.13.1)",
    "pymysql (==1.1.2)",
    "rank-bm25 (>=0.2.2)",
    "sentence-transformers (>=3.0.0)",
    "bcrypt (==5.0.0)",
    "streamlit (==1.54.0)",
    "requests (==2.32.5)",
    "python-dotenv (==1.2.1)",
    "psycopg[binary] (>=3.3.3,<4.0.0)",
    "sshtunnel (>=0.4.0,<0.5.0)",
    "paramiko (==3.5.0)",
    "sqlalchemy (>=2.0.46,<3.0.0)",
    "psycopg2-binary (>=2.9.11,<3.0.0)",
    "pgvector (>=0.4.2,<0.5.0)",
    "langgraph-checkpoint-postgres (>=3.0.4,<4.0.0)",
    "python-multipart (>=0.0.22,<0.0.23)",
    "python-jose[cryptography] (>=3.5.0,<4.0.0)",
    "torch (>=2.10.0,<3.0.0)",
    "torchvision (>=0.25.0,<0.26.0)",
    "torchaudio (>=2.10.0,<3.0.0)",
    "tavily-python (>=0.7.21,<0.8.0)",
    "langchain-tavily (>=0.2.17,<0.3.0)",
    "extra-streamlit-components (>=0.1.81,<0.2.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false